portfolio/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,  FloatField, SubmitField
from wtforms.validators import InputRequired, NumberRange

#Forms for everything to do with the portfolio section.

class PortfolioForm(FlaskForm):
    amount = FloatField(validators=[InputRequired(), NumberRange(min=0, max=9999999, message='Please enter a positive amount')])
    sell = SubmitField()

class SearchStock(FlaskForm):
    ticker_symbol = StringField()
    submit = SubmitField()


class BuyStock(FlaskForm):
    stock_amount = FloatField(validators=[InputRequired(), NumberRange(min=0, max=9999999, message='Please enter a positive amount')])
    buy = SubmitField()

class Listofstocks(FlaskForm):
    submit = SubmitField()

portfolio/views.py
from flask import Blueprint, redirect, url_for, render_template, request
from flask_login import login_required, current_user
import yfinance as yf
from app import db
from models import Stock, User
from portfolio.forms import PortfolioForm, SearchStock, BuyStock
from portfolio.search import searchforstock
import csv

portfolio_blueprint = Blueprint('portfolio', __name__, template_folder='templates')

#Page for the portfolio.

@portfolio_blueprint.route('/portfolio', methods=('GET', 'POST'))
@login_required
def portfolio():
    form = PortfolioForm()
    transactions = Stock.query.filter_by(id=current_user.id).all()

    profit_loss = 0

    #Update all the transactions current prices and therefore the profit amount.
    for i in transactions:
        new_price = searchforstock(f'{i.stock_symbol}')
        profit = (new_price-i.bought_price)*i.amount
        i.current_price=new_price
        i.profit_loss = profit
        profit_loss = profit_loss+(new_price*i.amount)
        db.session.commit()

    money = current_user.money
    totalassets = money+profit_loss

    if form.validate_on_submit():


        stockid = request.form.get("stockid","")

        stockQuery = Stock.query.filter_by(stock_id=stockid).all()

        #Checks if amount entered is suitable and then peforms the change.

        for i in stockQuery:

            if i.amount < form.amount.data:
                return redirect(url_for('portfolio.portfolio'))
            if i.amount == form.amount.data:

                totalprofit = i.amount * i.current_price
                current_user.money = current_user.money+totalprofit
                Stock.query.filter_by(stock_id=stockid).delete()
                db.session.commit()
                return redirect(url_for('portfolio.portfolio'))

            if i.amount > form.amount.data:
                totalprofit = form.amount.data * i.current_price
                current_user.money = current_user.money+totalprofit
                i.amount = i.amount - form.amount.data
                db.session.commit()

        return redirect(url_for('portfolio.portfolio'))

    return render_template('portfolio.html', form=form, transactions=transactions, money=money, name=current_user.first_name, totalassets=totalassets)


@portfolio_blueprint.route('/searchstock', methods=('GET', 'POST'))
@login_required
def searchstock():
    form = SearchStock()
    if form.validate_on_submit():

        output = searchforstock(f'{form.ticker_symbol.data}')

        #This checks that the search for stock wasn't found and if so queries the nasdaq database to find a potential match.

        if isinstance(output,str) == True:

            global list_stocks
            list_stocks = []

            global list_stocks_name
            list_stocks_name = []

            with open('nasdaq_screener.csv', newline='') as csvfile:
                data = list(csv.reader(csvfile))

            edited_user_input = form.ticker_symbol.data.lower()

            for i in data:

                string = ' '.join([str(item) for item in i])
                lower_string = string.lower()
                if edited_user_input in lower_string:
                    print(i[1])
                    print('The ticker symbol is: ' + i[0])
                    list_stocks.append(i[0])
                    list_stocks_name.append(i[1])

            #If there are no list of stocks then it will just reload the page.

            if list_stocks == []:
                return render_template('searchstock.html', form=form)

            return redirect(url_for('portfolio.listofstocks', list_stocks=list_stocks, list_stocks_name=list_stocks_name))



        global price
        price = float(output)
        global ticker
        ticker = form.ticker_symbol.data

        return redirect(url_for('portfolio.foundstock', ticker=ticker, price=price))
    return render_template('searchstock.html', form=form)

@portfolio_blueprint.route('/listofstocks', methods=('GET', 'POST'))
@login_required
def listofstocks():

    if request.method == 'POST':

        #By looping through in the HTML the submittion button is also assigned to whichever ticker symbol is presented.

        whichstock = request.form.get('whichstock')

        global ticker
        ticker = whichstock
        global price
        price = float(searchforstock(f'{ticker}'))

        return redirect(url_for('portfolio.foundstock', ticker=ticker, price=price))


    return render_template('listofstocks.html', output=list_stocks, output2=list_stocks_name)





@portfolio_blueprint.route('/foundstock', methods=('GET', 'POST'))
@login_required
def foundstock():
    form = BuyStock()

    money = current_user.money

    ticker_symbol = yf.Ticker(f'{ticker}')

    longName = 'longName'

    stock_long_name = ticker_symbol.info.get(longName)

    if stock_long_name:
        company_name = ticker_symbol.info['longName']
    else:
        company_name = ticker.upper()

    if form.validate_on_submit():

        new_transaction = Stock(id=current_user.id, stock_name=company_name, stock_symbol=ticker, amount=form.stock_amount.data, bought_price=price, current_price=price, profit_loss=0)

        userinformation = User.query.filter_by(id=current_user.id).all()

        for i in userinformation:
            if i.money < (form.stock_amount.data*price):
                return render_template('foundstock.html', output=price, company_name=company_name, form=form, ticker=ticker)
            old_money = i.money
            i.money = old_money-(form.stock_amount.data*price)
            db.session.add(new_transaction)
            db.session.commit()


        return redirect(url_for('portfolio.portfolio'))

    return render_template('foundstock.html', output=price, company_name=company_name, form=form, money=money)

users/views.py
from datetime import datetime

from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_user, logout_user
from sqlalchemy import func
from models import User
from app import db, index
from users.forms import RegisterForm, LoginForm
from flask_login import current_user, login_required
from werkzeug.security import check_password_hash

users_blueprint = Blueprint('users', __name__, template_folder='templates')


@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        max_id = db.session.query(func.max(User.id)).scalar()
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            flash('Email address already exists')
            return render_template('register.html', form=form)

        new_user = User(id=max_id + 1, email=form.email.data, password=form.password.data, first_name=form.firstname.data, role=user, money=10000)

        db.session.add(new_user)
        db.session.commit()

        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)


@users_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()

        if not user or not check_password_hash(user.password, form.password.data):

            flash('Please check your login details and try again')

            return render_template('login.html', form=form)

        login_user(user)
        user.current_logged_in = datetime.now()
        user.last_logged_in = user.current_logged_in
        db.session.add(user)
        db.session.commit()

        return index()

    return render_template('login.html', form=form)

@users_blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('index'))

templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="/static/stylesheet.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Arvo:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <title>UPortfolio</title>
</head>

<body>


<section>

    <div>
        <nav>
            <div>
                <div>
                    <div>
                        <a href="{{ url_for('index') }}" class="navbar-item">
                            Home
                        </a>
                    {% if not current_user.is_authenticated %}
                        <a href="{{ url_for('users.register') }}" class="navbar-item">
                            Register
                        </a>
                        <a href="{{ url_for('users.login') }}" class="navbar-item">
                            Login
                        </a>

                        {% endif %}
                        {% if current_user.is_authenticated %}
                        <a
                            href="{{ url_for('portfolio.portfolio') }}" class="navbar-item">
                            Portfolio
                        </a>
                        <a
                            href="{{ url_for('portfolio.searchstock') }}" class="navbar-item">
                            Search stock
                        </a>
                        <a href="{{ url_for('users.logout') }}" class="navbar-item">
                            Log out
                        </a>
                        {% endif %}
                    <a
                            href="{{ url_for('howitworks') }}" class="navbar-item">
                            How it works
                        </a>

                    </div>
                </div>
            </div>
        </nav>
    </div>
<footer>
    <p class="footer-text">Need help finding your ticker symbol? Find it here <br>
        <a href="https://uk.finance.yahoo.com/">Yahoo Finance</a>

    </p>
    </footer>

    <div>
        <div>
            {% block content %}
            {% endblock %}
        </div>
    </div>

</section>
</body>

</html>

templates/foundstock.html
{% extends "base.html" %}

{% block content %}

    <h1 class="bigpadding">Your cash: ${{ "{:.2f}".format(money) }}</h1>

    <div>
    <h1>${{ output }} for every share of {{ company_name }}</h1>

    <h2>Please select how much you would like to buy</h2>
    </div>

    <div>
     <form method="POST">
                {{ form.csrf_token() }}
                <div>
                    {{ form.stock_amount(class="input", placeholder="Amount of shares") }}
                    {% for error in form.stock_amount.errors %}
                            {{ error }}
                        {% endfor %}
                </div>
                    <br>
                <div>
                    {{ form.buy(class="button") }}

                </div>
            </form>
    </div>
    </div>


{% endblock %}

templates/how_it_works.html
{% extends "base.html" %}

{% block content %}

     <h1 class="main_header">How it works</h1>

    <h1>Every user starts with $10,000 in their portfolio.</h1>

    <h1>By using the stock search a user can enter a ticker symbol and then purchase any amount of that stock.</h1>

    <h1>Profit and loss is tracked in the 'Portfolio' page where you can also sell your stocks and view your current cash holdings.</h1>

    <footer>
    <p class="footer-text">Need help finding your ticker symbol? Find it here <br>
        <a href="https://uk.finance.yahoo.com/">Yahoo Finance</a>

    </p>
    </footer>

{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}

    <div class="img">

    <img src="/static/UPortfolioLogo.png" alt="Company Logo">
    
    </div>
    
<h1 class="main_header">Welcome to UPortfolio</h1>

{% endblock %}

templates/listofstocks.html
{% extends "base.html" %}

{% block content %}

<h1 class="main_header">List of the stocks: </h1>

    {% for i in range(output| length) %}

    <form method="POST" class="listofitems">

        {{ output2[i] }}  with the ticker symbol <input type="submit" value={{ output[i] }} name="whichstock"/>

    </form>

    {% endfor %}

{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

<h1>Login Page</h1>
    <div>

    {% with messages = get_flashed_messages() %}
                {% if messages %}
                    <div>
                        {{ messages[0] }}
                    </div>
                {% endif %}
            {% endwith %}


    <form method="POST">
                {{ form.csrf_token() }}
                <div>
                    {{ form.email(class="input", placeholder="Email") }}
                </div>
                {% for error in form.email.errors %}
                        {{ error }}
                    {% endfor %}
                    <br>
                <div>
                    {{ form.password(class="input", placeholder="Password") }}
                </div>
                {% for error in form.password.errors %}
                        {{ error }}
                    {% endfor %}
                    <br>
                <div>
                    {{ form.submit(class="button") }}
                </div>
            </form>
    </div>

{% endblock %}

templates/portfolio.html
{% extends "base.html" %}

{% block content %}

<h1 class="main_header">{{ name }}'s Portfolio</h1>

    <div>

    <h2>Your current cash holdings: ${{ "{:.2f}".format(money) }}</h2>

    <h2>Total asset worth: ${{ "{:.2f}".format(totalassets) }}</h2>


    </div>

    <div>
<h2>Your transactions:</h2>
    </div>

    <div>

    {% for i in transactions %}
        <form method="POST">
                {{ form.csrf_token() }}
            <h2>Transaction ID {{ i.stock_id }}</h2>
    <p>{{ i.amount }} shares of {{ i.stock_name }} at the price of {{ i.current_price }} with a profit of ${{ "{:.2f}".format(i.profit_loss) }}

    <div>
    {{ form.amount(class="input", placeholder="Enter amount") }}
            {% for error in form.amount.errors %}
                            {{ error }}
                        {% endfor %}
    </div>
        <br>
            <input value = {{ i.stock_id }} type="hidden" name="stockid">

        <div>
                    {{ form.sell(class="button") }}
                </div>

    </p>
        </form>
    {% endfor %}


</div>


{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}

<h1>Register Page</h1>

    <div>
    <form method="POST">
                {{ form.csrf_token() }}
                    <div>
                        {{ form.email(class="input", placeholder="Email") }}
                    </div>
                    {% for error in form.email.errors %}
                            {{ error }}
                        {% endfor %}

                        <br>
                    <div>
                        {{ form.password(class="input", placeholder="Password") }}
                    </div>
                    {% for error in form.password.errors %}
                            {{ error }}
                        {% endfor %}
                        <br>
                    <div>
                        {{ form.confirm_password(class="input", placeholder="Confirm Password") }}
                    </div>
                    {% for error in form.confirm_password.errors %}
                            {{ error }}
                        {% endfor %}
                        <br>
                    <div>
                        {{ form.firstname(class="input", placeholder="First Name") }}
                    </div>
                        {% for error in form.firstname.errors %}
                            {{ error }}
                        {% endfor %}
                        <br>
                    <div>
                        {{ form.submit(class="button") }}
                    </div>
            </form>
    </div>

{% endblock %}

templates/searchstock.html
{% extends "base.html" %}

{% block content %}

<h1 class="main_header">Search Stock</h1>
    <div>
    <form method="POST">
                {{ form.csrf_token() }}
                <div>
                    {{ form.ticker_symbol(class="input", placeholder="Enter the ticker symbol here") }}
                </div>
                    <br>
                <div>
                    {{ form.submit(class="button") }}
                </div>
            </form>
    </div>

{% endblock %}